version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./web:/web
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./web:/web
    links:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_passwd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - 8888:80
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=root_passwd
      - PHP_UPLOAD_MAX_FILESIZE=100MB
